#################
# zsh enviroment 
#################
# define path
NODE_BIN_PATH=/usr/local/node/bin
USER_APP_BIN_PATH=$HOME/app/bin
COMPOSER_BIN_PATH=$HOME/.composer/vendor/bin
PYTHON3_BIN_PATH=/usr/local/python3/bin
PHP7_BIN_PATH=/usr/local/php7/bin

# Use vim as the visual editor
export VISUAL=vim
export EDITOR=$VISUAL

# reset PATH
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/bin/X11:/usr/games
# add global 
[ -d $NODE_BIN_PATH ] && PATH=$NODE_BIN_PATH:$PATH
[ -d $COMPOSER_BIN_PATH ] && PATH=$COMPOSER_BIN_PATH:$PATH
[ -d $USER_APP_BIN_PATH ] && PATH=$USER_APP_BIN_PATH:$PATH
[ -d $PYTHON3_BIN_PATH ] && PATH=$PYTHON3_BIN_PATH:$PATH
[ -d $PHP7_BIN_PATH ] && PATH=$PHP7_BIN_PATH:$PATH
# add jre path
[ -f /etc/jrerc ] && . /etc/jrerc
# nvm mirror
export NVM_NODEJS_ORG_MIRROR=https://npm.taobao.org/dist
export NODEJS_ORG_MIRROR=https://npm.taobao.org/dist
# add nvm and local node path
if false && which nvm &> /dev/null;then
    if [ -f $HOME/.node-version ];then
        config_node_version=`cat $HOME/.node-version`
        if [ -n "$config_node_version" ];then
            node_version=$config_node_version
        fi
    else
        installed_latest=`nvm_ls | egrep -v "^(system|N/A)$" | tail -1`
        if [ -n $installed_latest ];then
            node_version=$installed_latest
        fi
    fi
    if [ -n "$node_version" ];then
        node_bin_path=${NVM_DIR}/versions/node/${node_version}/bin
        test -d $node_bin_path && PATH=${NVM_DIR}/versions/node/${node_version}/bin:$PATH
    fi
fi

# fast set proxy
set_proxy() {
    if [ ! $1 ]; then
        echo "No give proxy address"
        exit 1
    fi
    export HTTP_PROXY=$1
    export HTTPS_PROXY=$1
    export http_proxy=$1
    export https_proxy=$1
}
unset_proxy() {
    unset HTTP_PROXY
    unset HTTPS_PROXY
    unset http_proxy
    unset https_proxy
}
get_proxy() {
    echo "\$http_proxy: $http_proxy"
    echo "\$https_proxy: $https_proxy"
    echo "\$HTTP_PROXY: $HTTP_PROXY"
    echo "\$HTTPS_PROXY: $HTTPS_PROXY"
}

# register virtualenvwrapper
register_venv() {
    source `which virtualenvwrapper.sh`
}
# register virtualenvwrapper with python3
register_venv3() {
    export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
    export WORKON_HOME=$HOME/.virtualenvs3
    source `which virtualenvwrapper.sh`
}

# Local config
test -f ~/.zshenv.local && source ~/.zshenv.local

