# Install oh-my-zsh
# curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
# or
# wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O - | sh
#
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="robbyrussell"
if [[ -n $SSH_CONNECTION ]];then
    ZSH_THEME="xinmu"
fi

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="false"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"
export UPDATE_ZSH_DAYS=9999999

# Uncomment the following line to disable colors in ls.
DISABLE_LS_COLORS="false"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="false"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$HOME/.dotfiles/zsh/custom

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(z git pip virtualenvwrapper history nvm sudo)
# load plugin under X
if [[ -z $SSH_CONNECTION ]];then
    plugins=($plugins sublime)
fi

# load on my zsh
source $ZSH/oh-my-zsh.sh

# disable zsh auto correct
unsetopt correct_all
# disable mail check
unset MAILCHECK
# disable history share between sessions
unsetopt share_history
# this is the reason: http://forum.ubuntu.org.cn/viewtopic.php?f=21&t=284253
setopt nonomatch
# more match pattern
shopt -s extglob
# additional rc file
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
# personal aliases
[[ -f ~/.zsh_aliases ]] && source ~/.zsh_aliases
# environment setting
[[ -f ~/.zshenv ]] && source ~/.zshenv
