# Aliases
#
# Interactive operation...
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
#
# Default to human readable figures
alias df='df -h'
alias du='du -h'
#
# Misc :)
alias less='less -r'                          # raw control characters
alias whence='type -a'                        # where, of a sort
alias grep='grep --color'                     # show differences in colour
alias egrep='egrep --color=auto'              # show differences in colour
alias fgrep='fgrep --color=auto'              # show differences in colour
#
# Some shortcuts for different directory listings
alias ls='ls -h --color=auto'                 # classify files in colour
alias l.='ls -d .* --color=auto'
alias dir='ls --color=auto --format=vertical'
alias vdir='ls --color=auto --format=long'
alias ll='ls -l --color=auto'                 # long list
alias la='ls -A'                              # all but . and ..
alias l='ls -CF'                              #

# User specific aliases and functions
alias vi='vim'
alias py='python'
alias clean='echo -ne "\\033c"'

# Local config
[[ -f ~/.bash_aliases.local ]] && source ~/.bash_aliases.local
